// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJJ58cfkn_LwS_9V3kfhn0D14yLr0h-Q',
    appId: '1:305566117552:web:568ba044ee572a03e95575',
    messagingSenderId: '305566117552',
    projectId: 'cashly-c0acc',
    authDomain: 'cashly-c0acc.firebaseapp.com',
    storageBucket: 'cashly-c0acc.firebasestorage.app',
    measurementId: 'G-CEBS35TBMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTV1ZCJSvLYwfvlcDpx8ChUtJNnS8YX6k',
    appId: '1:305566117552:android:d89e01326edf5d39e95575',
    messagingSenderId: '305566117552',
    projectId: 'cashly-c0acc',
    storageBucket: 'cashly-c0acc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVXo-C5vfV7iBAJI7ziivj1MZid6vxiRc',
    appId: '1:305566117552:ios:4977e2c3afedefbce95575',
    messagingSenderId: '305566117552',
    projectId: 'cashly-c0acc',
    storageBucket: 'cashly-c0acc.firebasestorage.app',
    iosBundleId: 'com.example.cashly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVXo-C5vfV7iBAJI7ziivj1MZid6vxiRc',
    appId: '1:305566117552:ios:4977e2c3afedefbce95575',
    messagingSenderId: '305566117552',
    projectId: 'cashly-c0acc',
    storageBucket: 'cashly-c0acc.firebasestorage.app',
    iosBundleId: 'com.example.cashly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmJJ58cfkn_LwS_9V3kfhn0D14yLr0h-Q',
    appId: '1:305566117552:web:303aa5a8f042f16ae95575',
    messagingSenderId: '305566117552',
    projectId: 'cashly-c0acc',
    authDomain: 'cashly-c0acc.firebaseapp.com',
    storageBucket: 'cashly-c0acc.firebasestorage.app',
    measurementId: 'G-9E6F3GPM2S',
  );

}